# Generated by Django 2.2.2 on 2019-06-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=90)),
                ('value', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'vocabularies',
                'db_table': 'vocabulary',
                'unique_together': {('key', 'value')},
            },
        ),
    ]
