# Generated by Django 2.2.2 on 2019-06-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djvocab', '0002_auto_20190513_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='value',
            field=models.CharField(max_length=190),
        ),
    ]
