# Generated by Django 2.2.2 on 2019-06-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djvocab', '0003_auto_20190624_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='key',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
